### ISSUE TITLE
Git configuration hooks not finding gem extensions

### ISSUE THREAD

**Issue by christoff-1992** [bkuhlmann/dotfiles#2]
## Overview
When committing using the GitHub desktop client an error message is displayed stating that Git-cop can not be found. However this is installed on the local machine as it was part of the automated setup. I have also confirmed this is installed and have manually reinstalled the gem.

This looks to have been caused by the git.sh

```ruby
#! /usr/bin/env bash

# Label: Git Cop
# Description: Enforces consistent Git commits.
git_cop() {
  if ! command -v git-cop > /dev/null; then
     printf "%s\n" "[git]: Git Cop not found. To install, run: gem install git-cop --trust-policy MediumSecurity."
     exit 1
  fi

  git-cop --hook --commit-message "${BASH_ARGV[0]}"
}
```

## Screenshots/Screencasts
![screen shot 2017-11-24 at 09 11 08](https://user-images.githubusercontent.com/12499390/33203368-a6b1558c-d0f7-11e7-8ea2-c6cebd46f125.png)

## Environment
macOS High Sierra
iMac (27-inch, Late 2013)

**Comment by bkuhlmann** [comment]
Thanks. This doesn't sound like a Git Cop or Dotfiles issue, but more like an improper Bash environment configuration issue. If you have fully installed this Dotfiles project and adhered to the requirements of the project (including the [macOS Config](https://github.com/bkuhlmann/mac_os-config) requirements), then you'll not have issues as this is what I use for my working environment. If you haven't followed these steps and are only using a hybrid of this project by pulling in the pieces that you want then I can't help you much in that regard as that is beyond the scope of this project.

That said, I can point you in the right direction. You'll need to make sure your [.bash_profile](https://github.com/bkuhlmann/dotfiles/blob/master/home_files/.bash_profile.tt) and [.bashrc](https://github.com/bkuhlmann/dotfiles/blob/master/home_files/.bashrc.tt) are properly configured. In my case, I use [chruby](https://github.com/postmodern/chruby) as configured [here](https://github.com/bkuhlmann/dotfiles/blob/master/home_files/.bashrc.tt#L70-L74). All of this is critical to having a working environment that loads the correct version of Ruby and the related version of Git Cop correctly.
